//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cafe_system
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Cafe_system_DBEntities1 : DbContext
    {
        public static Cafe_system_DBEntities1 _context;
        public Cafe_system_DBEntities1()
            : base("name=Cafe_system_DBEntities1")
        {
        }

        public static Cafe_system_DBEntities1 GetContext()
        {
            if (_context == null)
            {
                _context = new Cafe_system_DBEntities1();

            }
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        //public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        //public virtual DbSet<tbCafeStuff> tbCafeStuff { get; set; }
        public virtual DbSet<Cafe_system_DBEntities1> tbProducts { get; set; }
        //public virtual DbSet<tbSmena> tbSmena { get; set; }
    }
}
